services:
  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: oracle-db
    ports:
      - "1522:1521"
    environment:
      ORACLE_ALLOW_REMOTE: "true"
      ORACLE_DISABLE_ASYNCH_IO: "true"
      ORACLE_PASSWORD: "Bada2024"
    volumes:
      - oracle-data:/opt/oracle/oradata

  app:
    build:
      context: .
    container_name: spring-boot-app
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521:FREE
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: Bada2024
    depends_on:
      - oracle-db

volumes:
  oracle-data:
    driver: local